### ISSUE TITLE
Throwing error in v.92

### ISSUE THREAD

**Issue by KittyDreadful** [VirToReal/Hardy-Hershey-Text#3]
hi,
This is the error that this being generated when I try to use the extension:
Traceback (most recent call last):
  File "hardyhershey.py", line 508, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "hardyhershey.py", line 500, in effect
    load_xml(self.options.xmlfile, self.options.layout, textlines, self.current_layer, self.document.getroot()) # Submit Layout
  File "hardyhershey.py", line 106, in load_xml
    xmldoc = minidom.parse(filename)
  File "C:\Program Files\Inkscape\lib\python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "C:\Program Files\Inkscape\lib\python2.7/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 13] Permission denied: 'C:\\Users\\kathomp\\Desktop\\HardyFolder'

I'm on a Windows machine
Inkscape 0.92.4 (5da689c313, 2019-01-14)

I've renamed the example.xml file to Layout 1.xml and saved in C:\Users\kathomp\desktop\hardyfolder   I don't know why the extra \s are being added.

**Comment by VirToReal** [comment]
Hi KittyDreadful,

in the tab "Layout" at "Source of Layout XML file" you have to write down the location itself of the XML file. In windows it should be something like "C:\Users\kathomp\desktop\hardyfolder\example.xml". Please try to avoid space in file or folder names (sorry the script is pritty easy on checking the path to the file). Never believed someone actually using this scipt ;-)

**Comment by KittyDreadful** [comment]
Hi,
Thanks for your email - Danke für Ihre E-Mail!

I followed the directions and used the full location of the file (C:\Users\kathomp\desktop\hardyfolder).  The source field works only when the layout.xml file is located in the extensions folder. 

Ich folgte den Anweisungen und verwendete den vollständigen Speicherort der File (C:\Users\kathomp\desktop\hardyfolder). Das Source Field funktioniert nur wenn sich die layout.xml File im extensions folder befindet.

I have moved the 'layout.xml' file to the extensions folder and the error stopped. 
Ich habe 'layout.xml' file in den extensions verschoben und der Fehler wurde gestoppt.    

Layout.xml is just the Example file with a new name.  But it still doesn't work.  No errors, but no text is rendered. 
Layout.xml ist nur  die Example.xml file mit eine neue Name.   Aber jetzt nichts gehts - keine Fehler, aber kein Text wird gerendert.  

Suggestions? 
Vorschläge?

**Comment by VirToReal** [comment]
hi,
I guess there is a problem in how inkscape is handling path-names in windows. I'm pretty sure the easy way I used doesn't work in windows. But I'm sorry, I have no windows and time around to validate. Try to use the file as you mentioned in the extensions folder. In the Tap "Text rendern" be sure to use as "Aktion" "Use Layout" instead of "Diesen Text setzen" and choose on of the "Layouts" of the dropdown menu. After that, the text you write down in "layout" Tap in Line 1 - 5 should be rendered like described in the selected layout and it's depending code in the xml file.

**Comment by KittyDreadful** [comment]
I've already tried 'use layout'.  Nothing renders.
